---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi-operator
spec:
  interval: 5m
  url: https://ceph.github.io/ceph-csi-operator
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chart:
    spec:
      chart: ceph-csi-drivers
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: ceph-csi-operator
  interval: 15m
  dependsOn:
    - name: rook-ceph
  values:
    drivers:
      cephfs:
        kernelMountOptions:
          ms_mode: prefer-crc
        nodePlugin:
          tolerations: &pluginTolerations
            - key: llm-workload
              operator: Exists
              effect: NoSchedule
      nfs:
        enabled: false
      nvmeof:
        enabled: false
      rbd:
        nodePlugin:
          tolerations: *pluginTolerations
    operatorConfig:
      namespace: rook-ceph
