---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/v1/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-ui-preferences
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: ceph-block
