---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: &name memory-mcp
spec:
  image: ghcr.io/bjw-s-labs/mcp-memory:2026.7.4@sha256:78487a16681b91102197e9b7915f950a148e94ff1ce6356707d3ff6ef6516ae7
  transport: stdio
  groupRef:
    name: mcp-tools
  podTemplateSpec:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: *name
      containers:
        - name: mcp
          volumeMounts:
            - name: data
              mountPath: /data
