---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ceph-csi-drivers
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.0.1
  url: oci://ghcr.io/home-operations/charts-mirror/ceph-csi-drivers
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
  interval: 15m
  dependsOn: []
  values:
    drivers:
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
        snapshotPolicy: volumeSnapshot
        kernelMountOptions:
          ms_mode: prefer-crc
        nodePlugin:
          tolerations: &pluginTolerations
            - key: llm-workload
              operator: Exists
              effect: NoSchedule
      nfs:
        enabled: false
      nvmeof:
        enabled: false
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        snapshotPolicy: volumeSnapshot
        nodePlugin:
          tolerations: *pluginTolerations
