---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
  interval: 15m
  dependsOn: []
  values:
    operatorConfig:
      driverSpecDefaults:
        controllerPlugin:
          resources:
            attacher:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            omapGenerator:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 1Gi
            plugin:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
            provisioner:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            resizer:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
            snapshotter:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
        nodePlugin:
          resources:
            plugin:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 1Gi
            registrar:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
    drivers:
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
        grpcTimeout: 150
        snapshotPolicy: volumeSnapshot
        kernelMountOptions:
          ms_mode: prefer-crc
        controllerPlugin:
          replicas: 2
        nodePlugin:
          tolerations: &pluginTolerations
            - key: llm-workload
              operator: Exists
              effect: NoSchedule
      nfs:
        enabled: false
      nvmeof:
        enabled: false
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        grpcTimeout: 150
        snapshotPolicy: volumeSnapshot
        controllerPlugin:
          replicas: 2
        nodePlugin:
          tolerations: *pluginTolerations
