---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lemonade-tts-cache
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 40Gi
