---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: localai
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: localai-secret
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: localai
        property: HF_TOKEN
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: localai
        property: OPENAI_API_KEY
