---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./gemma4-e4b.yaml
  - ./qwen2-5-coder-7b.yaml
  - ./qwen3-5-9b.yaml
