---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=custom.talos-factory depName=siderolabs/talos
    version: v1.13.7
  policy:
    timeout: 30m
    debug: true
    placement: hard
  drain:
    enabled: true
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
