---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alert-triage
spec:
  interval: 1h
  path: ./kubernetes/apps/base/observability/alert-triage
  postBuild:
    substitute:
      LOGS_URL: http://victoria-logs-server.observability.svc.cluster.local:9428
      LOGS_FLAVOR: victorialogs
      GRAFANA_URL: https://grafana.jory.dev
      GRAFANA_METRICS_DS: df062450-90bc-4bee-a5e7-08371b2919b8
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
