---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-server
spec:
  chartRef:
    kind: OCIRepository
    name: matter-server
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-iot",
            "namespace": "network",
            "ips": ["192.168.10.122/24"]
          }]
      hostUsers: false
      securityContext:
        sysctls:
          # Accept Thread OMR route advertisements on the Multus interface.
          - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
            value: "64"
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      matter-server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/matter-js/matterjs-server
              tag: 1.3.3@sha256:ac537ba44a2edaaf785b818f8b7ce75cdf736539401462046f0042670bee4063
            env:
              TZ: America/Edmonton
              MATTER_SERVER__INSTANCE_NAME: "{{ .Release.Name }}"
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host "{{ .Release.Name }}.jory.dev"
              MATTER_SERVER__LOG_LEVEL: info
            args:
              - --storage-path=/data
              - --primary-interface=net1
              - --log-level=debug
              - --production-mode
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
            resources:
              limits:
                memory: 1Gi
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir
    route:
      app:
        hostnames: [*host]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: *port
    service:
      app:
        ports:
          http:
            port: *port
