---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
  annotations:
    kopiur.home-operations.com/allow-identity-change: "true"
spec:
  compression:
    compressor: zstd
  credentialProjection:
    enabled: true
  mover:
    securityContext:
      runAsGroup: ${KOPIUR_PGID:=100}
      runAsUser: ${KOPIUR_PUID:=1000}
  repository:
    kind: ClusterRepository
    name: volsync
  retention:
    keepDaily: 7
    keepHourly: 24
    keepLatest: 3
    keepWeekly: 4
  sources:
    - pvc:
        name: ${APP}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
