---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: grafana
spec:
  remoteUrl: http://mcp-grafana.observability:8000/sse
  transport: sse
  groupRef:
    name: mcp-tools
