---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: forgejo-admin
spec:
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: forgejo
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: forgejo
          property: password
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    secret:
      name: forgejo-admin
