---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mcp-arr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        SONARR_URL: http://sonarr.downloads
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        RADARR_URL: http://radarr.downloads
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        PROWLARR_URL: http://prowlarr.downloads
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
  - extract:
      key: sonarr
  - extract:
      key: radarr
  - extract:
      key: prowlarr
