---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mcp-arr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    controllers:
      mcp-arr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
                repository: ghcr.io/joryirving/mcp-arr
                tag: 1.5.4@sha256:f0a5f6848bcb54c9bf17d9727c234f6ef9742a70919a94d843b3c216b1a098ee
            env:
              TZ: America/Edmonton
            envFrom:
              - secretRef:
                  name: mcp-arr
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: 3000
    route:
      app:
        hostnames: ["arr-mcp.jory.dev"]
        parentRefs:
          - name: envoy-internal
            namespace: network
