---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        CONTEXT7_API_KEY: "{{ .CONTEXT7_OPENCODE_API_KEY }}"
        GH_TOKEN: "{{ .GITHUB_TOKEN }}"
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
        LITELLM_API_KEY: "{{ .LITELLM_OPENCODE_API_KEY }}"
        MEMINI_API_KEY: "{{ .OPENCODE_API_KEY }}"
        OPENCODE_SERVER_PASSWORD: "{{ .OPENCODE_SERVER_PASSWORD }}"
  dataFrom:
    - extract:
        key: opencode
      rewrite:
        - regexp:
            source: ^password$
            target: OPENCODE_SERVER_PASSWORD
    - extract:
        key: context7
      rewrite:
        - regexp:
            source: ^OPENCODE_API_KEY$
            target: CONTEXT7_OPENCODE_API_KEY
    - extract:
        key: github-miso
    - extract:
        key: litellm
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        client-id: "{{ .OPENCODE_CLIENT_ID }}"
        client-secret: "{{ .OPENCODE_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: opencode
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode-htpasswd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        .htpasswd: "{{ .HTPASSWD }}"
  dataFrom:
    - extract:
        key: opencode
