---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: litellm
        property: LITELLM_OPENCODE_API_KEY
    - secretKey: CONTEXT7_API_KEY
      remoteRef:
        key: context7
        property: OPENCODE_API_KEY
    - secretKey: MEMINI_API_KEY
      remoteRef:
        key: opencode
        property: OPENCODE_API_KEY
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: github-miso
        property: GITHUB_TOKEN
    - secretKey: GH_TOKEN
      remoteRef:
        key: github-miso
        property: GITHUB_TOKEN
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
  data:
    - secretKey: client-id
      remoteRef:
        key: opencode
        property: OPENCODE_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: opencode
        property: OPENCODE_CLIENT_SECRET
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode-htpasswd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
  data:
    - secretKey: .htpasswd
      remoteRef:
        key: opencode
        property: HTPASSWD
