---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}"
        UI_USERNAME: "{{ .UI_USERNAME }}"
        UI_PASSWORD: "{{ .UI_PASSWORD }}"
        GENERIC_CLIENT_ID: "{{ .LITELLM_CLIENT_ID }}"
        GENERIC_CLIENT_SECRET: "{{ .LITELLM_CLIENT_SECRET }}"
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        MOONSHOT_API_KEY: "{{ .MOONSHOT_API_KEY }}"
        OPENCODE_API_KEY: "{{ .OPENCODE_API_KEY }}"
        ZAI_API_KEY: "{{ .ZAI_API_KEY }}"
  dataFrom:
    - extract:
        key: litellm
    - extract:
        key: minimax
    - extract:
        key: moonshot
    - extract:
        key: opencode
    - extract:
        key: z.ai
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: huggingface
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: huggingface
    template:
      data:
        HF_TOKEN: "{{ .HF_TOKEN }}"
  dataFrom:
    - extract:
        key: HuggingFace
