---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .password }}"
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
  dataFrom:
    - extract:
        key: litellm
