---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
  - ./ornith1.0-35b.yaml
  - ./qwen3.5-4b.yaml
  - ./qwen3.6-27b.yaml
  # - ./qwen3.6-35b.yaml
  - ./servicemonitor.yaml
  - ./dashboard
