---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmkube-skirk-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 500Gi
