---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr-mcp
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    controllers:
      seerr-mcp:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jhomen368/overseerr-mcp
              tag: 2.1.2
            env:
              TZ: America/Edmonton
            envFrom:
              - secretRef:
                  name: seerr-mcp
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: 8085
    route:
      app:
        hostnames: ["seerr-mcp.jory.dev"]
        parentRefs:
          - name: envoy-internal
            namespace: network
