apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
patches:
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: not-used
    spec:
      install:
        crds: CreateReplace
      rollback:
        cleanupOnFail: true
        recreate: true
      timeout: 10m
      upgrade:
        cleanupOnFail: true
        crds: CreateReplace
        strategy:
          name: RemediateOnFailure
        remediation:
          remediateLastFailure: true
          retries: 2
  target:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
resources:
- ./clustersecretstore.yaml
- ./grafanadashboard.yaml
- ./helmrelease.yaml
