---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mission-control
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      mission-control:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/mission-control
              tag: 2.0.0@sha256:d84088405a285257f62e380b1736ac8e510830c0aac2256210a4d8d88c4a6ed4 
            env:
              OPENCLAW_GATEWAY_HOST: "openclaw.llm"
              NEXT_PUBLIC_GATEWAY_URL: "wss://miso.jory.dev"
              MC_ALLOWED_HOSTS: "mission-control.jory.dev"
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: 3000
    route:
      app:
        hostnames: ["mission-control.jory.dev"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/.data
