---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-auto-languages
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    controllers:
      plex-auto-languages:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/journeydocker/plex-auto-languages
              tag: 1.5.0@sha256:018caee713a6695aa7b6b2b8c19d277593cd0da50a3c72ec95af6cbe81a3d2a3
            env:
              TZ: America/Edmonton
              PLEX_URL: "http://plex.media.svc.cluster.local:32400"
            envFrom:
              - secretRef:
                  name: plex-secret
            resources:
              requests:
                cpu: 75m
                memory: 300M
              limits:
                memory: 600M
