---
name: coturn

services:
  coturn:
    container_name: coturn
    command:
      - --log-file=stdout
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
    # renovate: datasource=docker depName=docker.io/coturn/coturn
    image: docker.io/coturn/coturn:4.15.0-r0@sha256:0feee4fc1f45c7c053c8fee3e1ab941b1a1b9a0429bc01e18126735410770bfd
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
