---
name: coturn

services:
  coturn:
    container_name: coturn
    command:
      - --log-file=stdout
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
    # renovate: datasource=docker depName=docker.io/coturn/coturn
    image: docker.io/coturn/coturn:4.17.0-r0@sha256:7df59bcd84800c3978da2dd0d7fb17a8179e77a8bf667f678813120a9f18b094
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
