---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thelounge
spec:
  chartRef:
    kind: OCIRepository
    name: thelounge
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      thelounge:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/thelounge/thelounge
              tag: 4.5.2@sha256:ec3e798d7d9243e49f4f268a4d83c03606fb7e8ace07191e8d1260faceb68d13
            env:
              THELOUNGE_HOME: /config
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
    route:
      app:
        hostnames: ["tl.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: 9000
