---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-swap-config-single
  namespace: llm
data:
  config.yaml: |
    windowSize: 5
    logLevel: "DEBUG"
    models:
      qwen27b:
        cmd: >-
          /usr/local/bin/llama-server
          --host 127.0.0.1
          --port 9001
          --model /models/BF16/Qwen3.5-27B-BF16-00001-of-00002.gguf
          --mmproj /models/qwen27b-mmproj-F32.gguf
          --ctx-size 131072
          --n-gpu-layers 99
          --flash-attn on
          --parallel 4
          --cont-batching
          --cache-prompt
          --temp 0.6
          --top-p 0.95
          --top-k 20
          --min-p 0
          --batch-size 2048
          --mmap
          --numa distribute
          --chat-template chatml
          --jinja
          --swa-full
        proxy: http://127.0.0.1:9001
        ttl: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-swap-config-dual
  namespace: llm
data:
  config.yaml: |
    windowSize: 5
    logLevel: "DEBUG"
    groups:
      always-on:
        swap: false
        exclusive: false
        members:
          - qwen35b
          - qwen3-coder
    models:
      qwen35b:
        cmd: >-
          /usr/local/bin/llama-server
          --host 127.0.0.1
          --port 9001
          --model /models/Qwen3.5-35B-A3B-heretic.Q4_K_M.gguf
          --mmproj /models/mmproj-F32.gguf
          --ctx-size 131072
          --n-gpu-layers 99
          --flash-attn on
          --parallel 2
          --cont-batching
          --cache-prompt
          --temp 0.6
          --top-p 0.95
          --top-k 20
          --min-p 0
          --cache-type-k q8_0
          --cache-type-v q8_0
          --batch-size 2048
          --mmap
          --numa distribute
          --chat-template chatml
          --reasoning-budget 0
          --jinja
          --swa-full
        proxy: http://127.0.0.1:9001
        ttl: 0
        group: qwen

      qwen3-coder:
        cmd: >-
          /usr/local/bin/llama-server
          --host 127.0.0.1
          --port 9002
          --model /models/Qwen3-Coder-Next-UD-Q4_K_XL.gguf
          --ctx-size 131072
          --n-gpu-layers 99
          --flash-attn on
          --parallel 2
          --cont-batching
          --cache-prompt
          --cache-type-k q8_0
          --cache-type-v q8_0
          --batch-size 2048
          --mmap
          --numa distribute
          --temp 0.4
          --top-p 0.95
          --top-k 20
          --jinja
          --reasoning-budget 0
        proxy: http://127.0.0.1:9002
        ttl: 0
        group: coder
