---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llama-embed
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: llama-embed
      app.kubernetes.io/instance: llama-embed
  namespaceSelector:
    matchNames:
      - llm
  targetLabels: ["app.kubernetes.io/name", "app.kubernetes.io/instance"]
  endpoints:
    - port: http
      path: /metrics
  fallbackScrapeProtocol: PrometheusText0.0.4
