---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanban
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    controllers:
      kanban:
        containers:
          app:
            image:
              repository: ghcr.io/kanboard/kanboard
              tag: v1.2.52@sha256:8cd46677f1f3b97bb45e8bcf30512ab92f30a9578cee51b406d2dd297a223859
            env:
              TZ: America/Edmonton
              PLUGIN_INSTALLER: "true"
            envFrom:
              - secretRef:
                  name: kanban
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 100
            fsGroup: 100
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      app:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames: ["kanban.jory.dev"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
