---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./coder.yaml
  - ./coder-frontier.yaml
  - ./coder-revision.yaml
  - ./reviewer.yaml
  - ./reviewer-fork.yaml
