---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoymiles-mqtt
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 15m
  dependsOn:
    - name: mosquitto
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      hoymiles-mqtt:
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/hoymiles-mqtt
              tag: 0.11.0@sha256:fda2e9917324ad988290bd1363860569b4aa61ae86a9eb30ef3ece8ed68a7a7d
            env:
              TZ: America/Edmonton
              DTU_HOST: solar.internal
              LOG_TO_CONSOLE: true
              MQTT_BROKER: mosquitto
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
