---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: status
    group: cluster
    url: https://status.jory.dev
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: utility-status
    group: cluster
    url: https://status-utility.jory.dev
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: towonel-hub
    group: columbina
    url: http://towonel-hub:8443/v1/health
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: cloudflare
    group: connectivity
    url: tcp://1.1.1.1:53
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: quad9
    group: connectivity
    url: tcp://9.9.9.9:53
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: sqlite
  caching: true
  path: /config/gatus.db

ui:
  title: Columbina Status
  header: Columbina Status
  logo: https://avatars.githubusercontent.com/u/46251616
  link: https://github.com/joryirving/home-ops
  buttons:
    - name: Status
      link: https://status.jory.dev
    - name: Utility Status
      link: https://status-utility.jory.dev

web:
  port: 8080
