---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: llm
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: llm
  rules:
    - matches:
        - headers:
            - name: x-ai-eg-model
              value: self-hosted
      backendRefs:
        - name: llama-memory
          modelNameOverride: self-hosted
      timeouts:
        request: 300s
    - matches:
        - headers:
            - name: x-ai-eg-model
              value: memory
      backendRefs:
        - name: llama-server
          modelNameOverride: memory
      timeouts:
        request: 300s
    - matches:
        - headers:
            - name: x-ai-eg-model
              value: vision
      backendRefs:
        - name: llama-vision
          modelNameOverride: qwen-vision
      timeouts:
        request: 300s
