---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: llama-server
spec:
  endpoints:
    - fqdn:
        hostname: llama-server.llm.svc.cluster.local
        port: 8080
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: llama-memory
spec:
  endpoints:
    - fqdn:
        hostname: llama-memory.llm.svc.cluster.local
        port: 8080
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: llama-vision
spec:
  endpoints:
    - fqdn:
        hostname: llama-vision.llm.svc.cluster.local
        port: 8080
