---
apiVersion: gateway.gateway.envoyproxy.io/v1
kind: Backend
metadata:
  name: llama-server
spec:
  endpoints:
    - fqdn: llama-server.llm.svc.cluster.local
      port: 8080
---
apiVersion: gateway.gateway.envoyproxy.io/v1
kind: Backend
metadata:
  name: llama-memory
spec:
  endpoints:
    - fqdn: llama-memory.llm.svc.cluster.local
      port: 8080
---
apiVersion: gateway.gateway.envoyproxy.io/v1
kind: Backend
metadata:
  name: llama-vision
spec:
  endpoints:
    - fqdn: llama-vision.llm.svc.cluster.local
      port: 8080
