---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: llm
spec:
  connection:
    bufferLimit: 51200
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
