---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: talos-mcp
spec:
  image: registry.erwanleboucher.dev/eleboucher/talos-mcp:0.0.2
  transport: streamable-http
  mcpPort: 8080
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: TALOS_MCP_TRANSPORT
      value: http
    - name: TALOS_MCP_HTTP_ADDR
      value: ":8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          volumeMounts:
            - name: talosconfig
              mountPath: /var/run/secrets/talos.dev
              readOnly: true
      volumes:
        - name: talosconfig
          secret:
            secretName: talos-mcp-talosconfig
            defaultMode: 0400
