---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: llama-ryzen-gpu
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly:
            deviceClassName: gpu.amd.com
