---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-cobbleverse
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft-cobbleverse
  interval: 15m
  dependsOn: []
  values:
    extraEnv:
      TZ: America/Edmonton
      MODPACK_PLATFORM: "MODRINTH"
      MODRINTH_MODPACK: "https://modrinth.com/modpack/cobbleverse"
      MODRINTH_VERSION: "1.7.30"
      MODRINTH_EXCLUDE_FILES: "mods/modmenu-*.jar,mods/RoughlyEnoughItems-*.jar,mods/sound-physics-remastered-*-fabric-*.jar,mods/moreculling-fabric-*.jar,mods/infinite-music-*.jar,mods/MusicNotification-*.jar,mods/Ping-Wheel-*.jar,mods/particle-rain-*.jar,mods/paginatedadvancements-*.jar,mods/notenoughcrashes-*.jar,mods/respackopts-*.jar,mods/defaultoptions-*.jar"
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.7.2-java21@sha256:7f69fd6688e03495c8a8f5a46e8a8e82001b4465f4b55bdcd024c02c3624d8c8
    livenessProbe:
      initialDelaySeconds: 30
    minecraftServer:
      eula: true
      # renovate: pinVersion=1.21.1
      version: 1.21.1
      # type: FABRIC
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=85"
      jvmOpts: "-Xms4G -Xmx8G"
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      #whitelist: "LilDrunkenSmurf"
      ops: "LilDrunkenSmurf,inadequatecircle,dumb_tako"
      motd: "cobbleverse for you."
      worldSaveName: cobbleverse
      viewDistance: 12
      modrinth:
        downloadDependencies: optional
      rcon:
        enabled: true
        existingSecret: *app
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    readinessProbe:
      initialDelaySeconds: 30
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 12
        memory: 12Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 100
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: cobbleverse.jory.dev
    startupProbe:
      enabled: true
