---
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: App
metadata:
  name: firefox
spec:
  appAssetWebP: UklGRhwBAABXRUJQVlA4IBABAADQHACdASosAZABPm02mUmkIqKhICgAgA2JaW7hd2EbQAnsA99snIe+2Yy09snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPfbJyHvtk5D32ych77ZOQ99snIe+2TkPekAAD+/9O4f/1K366KRn9B8NO3tyIAAAAAAAAAAAAAAAAAA
  deviceClassName: gow-wolf
  id: 1
  isHDRSupported: false
  template:
    spec:
      containers:
        - env:
            - name: RUN_SWAY
              value: '1'
          image: ghcr.io/games-on-whales/firefox:edge@sha256:1ea7331934d31d346079fb67462b371586d65b5ebb792acee8c0e64e87c185b1
          name: app
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 4Gi
            claims:
              - name: amd-gpu
          volumeMounts:
            - mountPath: /home/retro
              name: home
      nodeSelector:
        kubernetes.io/hostname: skirk
      resourceClaims:
        - name: amd-gpu
          resourceClaimName: gow-amd-gpu
      tolerations:
        - effect: NoSchedule
          key: llm-workload
          operator: Exists
      volumes:
        - emptyDir: {}
          name: home
  title: Firefox
