---
# yaml-language-server: $schema=https://raw.githubusercontent.com/shrinedogg/fenrir/main/schemas/direwolf.games-on-whales.github.io/app.json
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: App
metadata:
  name: testball
spec:
  appAssetWebP: UklGRlQAAABXRUJQVlA4IEgAAADQHQCdASKShYsoBDAqD0IaqbUZmPk4EnHR8QBs
  id: 1
  isHDRSupported: true
  title: Test Ball
  wolfConfig:
    audio:
      source: audiotestsrc wave=ticks is-live=true
    runtimeVariables:
      renderNode: /dev/dri/renderD128
    startAudioServer: false
    startVirtualCompositor: false
    video:
      source: |
        videotestsrc pattern=ball flip=true is-live=true !
        video/x-raw, framerate={fps}/1
