---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: games-on-whales
spec:
  chartRef:
    kind: OCIRepository
    name: direwolf-operator
  interval: 1h
  dependsOn: []
  values:
    controllers:
      direwolf_operator:
        containers:
          operator:
            image:
              repository: docker.io/shrinedogg/direwolf-operator
              tag: v0.1.0
              digest: sha256:398681deb415a4220fd3c68c6c500dbd2f5251f458be716e8663dd5152516df6
            args:
              - "--lb-sharing-key=direwolf"
            env:
              AGENT_IMAGE: docker.io/shrinedogg/wolf-agent:v0.1.0@sha256:1205f62ab4f4dd8cde97387e0055beba62cfe673f91df4ebe38aee0d4cf3cc08
              WOLF_IMAGE: docker.io/shrinedogg/wolf:v0.1.0@sha256:9d062c45ed7533ba5949db3d739448a83aa6c85a712a41193c496d4b6c1158f8
      moonlight_proxy:
        containers:
          proxy:
            image:
              repository: docker.io/shrinedogg/moonlight-proxy
              tag: v0.1.1
              digest: sha256:e8b7cf17ea1bab75c1cec1889a1166ebb3da4c5f0972ae8a7d7cc8dc2571fef0
    service:
      app:
        annotations:
          lbipam.cilium.io/ips: 10.69.10.43
          lbipam.cilium.io/sharing-key: direwolf
    serviceAccount:
      games-on-whales: {}
