---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./apps.yaml
  - ./certificate.yaml
  - ./deviceclass.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./profile.yaml
  - ./rbac.yaml
  - ./resourceclaim.yaml
  - ./wolf-config.yaml
