---
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: Profile
metadata:
  name: default
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  apps:
    - name: firefox
    - name: testball
    - name: steam
  pairings: []
