---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app miso-chat
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    controllers:
      miso-chat:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/miso-chat
              tag: 0.4.15@sha256:056b7d083754b406f10068e87b1b11349d60ef431126b492276c61e73ec78c2f
            env:
              REDIS_URL: "redis://{{ .Release.Name }}-dragonfly:6379"
              GATEWAY_DEVICE_IDENTITY_PATH: &path /secrets/device.json
              CORS_ORIGIN: "https://miso-chat.jory.dev"
              SESSION_COOKIE_SAMESITE: "none"
              SESSION_COOKIE_SECURE: "true"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: 3000
    route:
      app:
        hostnames: ["miso-chat.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
        # rules:
        #   - backendRefs: [{}]
        #     sessionPersistence:
        #       sessionName: *app
        #       type: Cookie
        #       absoluteTimeout: 35m
    persistence:
      miso-chat-device:
        type: secret
        name: "{{ .Release.Name }}-device"
        globalMounts:
          - path: *path
            subPath: device.json
