---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-collector
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.6
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-collector
  interval: 1h
  values:
    fullnameOverride: victoria-logs-collector
    podMonitor:
      enabled: true
    remoteWrite:
      - url: http://victoria-logs-server.observability.svc.cluster.local:9428
        maxDiskUsagePerURL: 10GB
    collector:
      streamFields:
        - kubernetes.pod_name
        - kubernetes.pod_namespace
        - kubernetes.container_name
        - kubernetes.pod_labels.app.kubernetes.io/name
    extraArgs:
      "kubernetesCollector.decolorizeFields": _msg
    tolerations:
      - operator: Exists
        effect: NoSchedule
