---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name synapse
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        MATRIX_ADMIN_PASSWORD: "{{ .MATRIX_ADMIN_PASSWORD }}"
        MATRIX_REGISTRATION_SHARED_SECRET: "{{ .MATRIX_REGISTRATION_SHARED_SECRET }}"
        MATRIX_OIDC_CLIENT_ID: "{{ .MATRIX_CLIENT_ID }}"
        MATRIX_OIDC_CLIENT_SECRET: "{{ .MATRIX_CLIENT_SECRET }}"
        signing.key: "{{ .MATRIX_SIGNING_KEY }}"
        log.config: |
          version: 1
          formatters:
            precise:
              format: "%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s"
          handlers:
            console:
              class: logging.StreamHandler
              formatter: precise
          loggers:
            synapse.storage.SQL:
              level: INFO
          root:
            level: INFO
            handlers: [console]
          disable_existing_loggers: false
        homeserver.yaml: |
          server_name: "matrix.jory.dev"
          public_baseurl: "https://matrix.jory.dev/"
          pid_file: /data/homeserver.pid
          log_config: "/data/log.config"
          soft_file_limit: 0

          listeners:
            - port: 8008
              tls: false
              type: http
              x_forwarded: true
              bind_addresses: ["0.0.0.0"]
              resources:
                - names: [client]
                  compress: false

          database:
            name: psycopg2
            allow_unsafe_locale: true
            args:
              host: synapse-rw.workadventure.svc.cluster.local
              port: 5432
              user: synapse
              database: synapse
              cp_min: 5
              cp_max: 10

          media_store_path: /data/media
          max_upload_size: 50M
          max_image_pixels: 32M
          url_preview_enabled: false

          enable_registration: false
          registration_shared_secret: "{{ .MATRIX_REGISTRATION_SHARED_SECRET }}"
          macaroon_secret_key: "{{ .MATRIX_MACAROON_SECRET_KEY }}"

          signing_key_path: "/data/signing.key"

          federation_domain_whitelist: []
          suppress_key_server_warning: true
          trusted_key_servers: []

          report_stats: false

          presence:
            enabled: true

          user_directory:
            enabled: true
            search_all_users: true

          rc_message:
            per_second: 1000
            burst_count: 1000
          rc_registration:
            per_second: 1000
            burst_count: 1000
          rc_login:
            address:
              per_second: 1000
              burst_count: 1000
            account:
              per_second: 1000
              burst_count: 1000
            failed_attempts:
              per_second: 1000
              burst_count: 1000

          oidc_providers:
            - idp_id: authentik
              idp_name: "Authentik"
              issuer: "https://sso.jory.dev/application/o/matrix/"
              client_id: "{{ .MATRIX_OIDC_CLIENT_ID }}"
              client_secret: "{{ .MATRIX_OIDC_CLIENT_SECRET }}"
              scopes: ["openid", "profile", "email"]
              user_profile_provider: "oidc"
              user_mapping_provider:
                config:
                  subject: sub
                  email: email
                  display_name: name
                  picture: profile_picture
  dataFrom:
    - extract:
        key: matrix
