---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
spec:
  chartRef:
    kind: OCIRepository
    name: synapse
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 991
        runAsGroup: 991
        fsGroup: 991
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      synapse:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/element-hq/synapse
              tag: v1.156.0@sha256:d2215c4a0e0bbd304489af228345b31d6857c1a228175471358d3fda187c0d91
            env:
              SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
              PGPASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-app"
                    key: password
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
            ports:
              - name: http
                containerPort: 8008
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: http
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 384Mi
              limits:
                memory: 1Gi
    persistence:
      config:
        type: secret
        name: synapse
        globalMounts:
          - path: /data/homeserver.yaml
            subPath: homeserver.yaml
            readOnly: true
          - path: /data/log.config
            subPath: log.config
            readOnly: true
          - path: /data/signing.key
            subPath: signing.key
            readOnly: true
      data:
        existingClaim: synapse
        globalMounts:
          - path: /data
    route:
      app:
        hostnames: ["matrix.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    service:
      app:
        controller: synapse
        ports:
          http:
            port: 8008
