---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miso-gallery
  namespace: llm
spec:
  chartRef:
    kind: OCIRepository
    name: miso-gallery
  interval: 15m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      miso-gallery:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/misospace/miso-gallery
              tag: 0.1.19@sha256:a86ba490fee4fa967a1fdcd73a3eb7615c171e5e9ce68063fd3def2920655840
            env:
              IMAGE_BASE_URL: https://miso-gallery.jory.dev
            envFrom:
              - secretRef:
                  name: miso-gallery
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
    persistence:
      data:
        type: nfs
        server: voyager.internal
        path: /mnt/daena/comfyui/output
    route:
      app:
        hostnames: ["miso-gallery.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: 5000
