---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm-operator
spec:
  chartRef:
    kind: OCIRepository
    name: litellm-operator
  interval: 15m
  values:
    controller:
      logLevel: info
      leaderElection:
        enabled: true
    llmkube:
      autoRegister: true
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        memory: 512Mi
