---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-jellycraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft-jellycraft
  interval: 15m
  dependsOn: []
  values:
    extraEnv:
      TZ: America/Edmonton
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.6.1@sha256:2a3ed0997720d79b7ed783a79e43143358b2e60d27daf15c2b1d27b59d04a6d8
    livenessProbe:
      initialDelaySeconds: 30
    minecraftServer:
      eula: true
      # renovate: datasource=custom.minecraft-release
      version: 26.2
      type: PAPER
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      #whitelist: "LilDrunkenSmurf"
      ops: "LilDrunkenSmurf"
      motd: "Jellycraft for you."
      worldSaveName: jellycraft
      viewDistance: 12
      spigetResources:
        - 36618 #Prom Exporter
      rcon:
        enabled: true
        existingSecret: *app
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    readinessProbe:
      initialDelaySeconds: 30
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 2000m
        memory: 4Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 100
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: jellycraft.jory.dev
    startupProbe:
      enabled: true
