---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minecraft-jellycraft
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.2
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-jellycraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft-jellycraft
  interval: 15m
  dependsOn: []
  values:
    extraEnv:
      TZ: America/Edmonton
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 
        2026.4.2@sha256:13b19d4134d236de47320e937d456b38bbc148db2bbab4a81064a3e71dbe37ad
    livenessProbe:
      initialDelaySeconds: 30
    minecraftServer:
      eula: true
      # renovate: datasource=custom.minecraft-release
      version: 26.1.2
      type: PAPER
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      #whitelist: "LilDrunkenSmurf"
      ops: "LilDrunkenSmurf"
      motd: "Jellycraft for you."
      worldSaveName: jellycraft
      viewDistance: 12
      spigetResources:
      - 36618 #Prom Exporter
      rcon:
        enabled: true
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    readinessProbe:
      initialDelaySeconds: 30
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 2000m
        memory: 4Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 100
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: jellycraft.jory.dev
    startupProbe:
      enabled: true
  valuesFrom:
  - kind: Secret
    name: *app
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password
