# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name terraform-backend-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        access_key: "{{ .TERRAFORM_STATE_KEY_ID }}"
        secret_key: "{{ .TERRAFORM_STATE_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: garage
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name terraform-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        OP_CONNECT_TOKEN: "{{ .OP_CONNECT_TOKEN }}"
        OP_CONNECT_HOST: "http://onepassword-connect.external-secrets.svc.cluster.local"
  dataFrom:
    - extract:
        key: 1password
