---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tofu-controller
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.16.3
  url: oci://ghcr.io/flux-iac/charts/tofu-controller
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  interval: 15m
  dependsOn: []
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
    runner:
      image:
        repository: ghcr.io/joryirving/opentofu-runner
        tag: 1.12.1@sha256:422e0a650df9f6fbb0955140ab271854bc2b83dd196875a636d8253b698ad8b5
