---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name waypoint
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # OAUTH
        WAYPOINT_OIDC_NAME: Authentik
        WAYPOINT_OIDC_ISSUER_URL: https://sso.jory.dev/application/o/waypoint//
        WAYPOINT_OIDC_CLIENT_ID: "{{ .WAYPOINT_CLIENT_ID }}"
        WAYPOINT_OIDC_CLIENT_SECRET: "{{ .WAYPOINT_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: waypoint
