---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: waypoint
spec:
  chartRef:
    kind: OCIRepository
    name: waypoint
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      waypoint:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/ctrl-research/waypoint
              tag: 0.0.14@sha256:0c2bd36a64834e404d9ea79b4c394b9e9b16136a693fbd120110e1f64fde79a3
            env:
              WAYPOINT_BASE_URL: https://travel.jory.dev
              WAYPOINT_DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-app"
                    key: fqdn-uri
              WAYPOINT_LANGUAGE: en
              WAYPOINT_LOCAL_AUTH: false
              WAYPOINT_MAP_STYLE_URL: https://tiles.openfreemap.org/styles/liberty
              WAYPOINT_MCP: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
    route:
      app:
        hostnames: ["travel.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
