---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrob
spec:
  chartRef:
    kind: OCIRepository
    name: scrob
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
    controllers:
      scrob:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/ellite/scrob
              tag: 2.11.0@sha256:58a37fdf7e27d39de2f1ce3116b1d507cec2543b5aa3ba2cb5eff39d2ac5c9b1
            env:
              POSTGRES_DB: "{{ .Release.Name }}"
              POSTGRES_HOST: "{{ .Release.Name }}-rw.media.svc.cluster.local"
              POSTGRES_PORT: "5432"
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-app"
                    key: password
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-app"
                    key: username
              TZ: America/Edmonton
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/backend/data
      tmpfs:
        type: emptyDir
        advancedMounts:
          scrob:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames: ["{{ .Release.Name }}.jory.dev"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 7330
