---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes
    template:
      data:
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
        TELEGRAM_ALLOWED_USERS: "{{ .TELEGRAM_ALLOWED_USERS }}"
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        MOONSHOT_API_KEY: "{{ .MOONSHOT_API_KEY }}"
        COMPOSIO_API_KEY: "{{ .COMPOSIO_API_KEY }}"
        ITS_MISO_PAT: "{{ .ITS_MISO_PAT }}"
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_PERSONAL_ACCESS_TOKEN }}"
  dataFrom:
    - extract:
        key: hermes-agent
