---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes
    template:
      data:
        COMPOSIO_API_KEY: "{{ .COMPOSIO_API_KEY }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_BOT_TOKEN: "{{ .SAKE_BOT_TOKEN }}"
        DISCORD_HOME_CHANNEL: "{{ .SAKE_HOME_CHANNEL }}"
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_TOKEN }}"
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        TELEGRAM_HOME_CHANNEL: "{{ .TELEGRAM_ALLOWED_USERS }}"
        TELEGRAM_ALLOWED_USERS: "{{ .TELEGRAM_ALLOWED_USERS }}"
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
        MEMINI_API_KEY: "{{ .MEMINI_API_KEY }}"
  dataFrom:
    - extract:
        key: hermes-agent
    - extract:
        key: github-miso
    - extract:
        key: composio
    - extract:
        key: litellm
    - extract:
        key: memini
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-dashboard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes
    template:
      data:
        HERMES_DASHBOARD_OIDC_CLIENT_ID: "{{ .HERMES_CLIENT_ID }}"
        HERMES_DASHBOARD_OIDC_CLIENT_SECRET: "{{ .HERMES_CLIENT_SECRET }}"
        HERMES_DASHBOARD_OIDC_ISSUER: https://sso.jory.dev/application/o/hermes-agent
  dataFrom:
    - extract:
        key: hermes-agent
