---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr-node
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      resourceClaims:
      - name: gpu
        resourceClaimTemplateName: tdarr-node-gpu
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/gpus
                operator: DoesNotExist
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
      labels:
        igpu-workload: "true"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              igpu-workload: "true"
    controllers:
      tdarr-node:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node
              tag: 
                2.75.01@sha256:db2b52a1a6fb545a9b0a45952d7f1172e1e23979af638845aea2a76ce2e2e7e6
            env:
              TZ: America/Edmonton
              serverIP: voyager.internal
              serverPort: 8266
              inContainer: true
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              claims:
              - name: gpu
              requests:
                cpu: 100m
              limits:
                cpu: 2000m
    persistence:
      media:
        type: nfs
        server: voyager.internal
        path: /mnt/akademiya/data/metube
        globalMounts:
        - path: /mnt/media
    service:
      app:
        enabled: false
