---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr-node
spec:
  chartRef:
    kind: OCIRepository
    name: tdarr-node
  interval: 15m
  dependsOn: []
  values:
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: tdarr-node-gpu
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/gpus
                    operator: DoesNotExist
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
      labels:
        igpu-workload: "true"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              igpu-workload: "true"
    controllers:
      tdarr-node:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node
              tag: 2.78.01@sha256:1ec96caf6735d3c1bae5e71540cfb686bfa3ad960eff5a2a526cc68e53551779
            env:
              TZ: America/Edmonton
              serverIP: voyager.internal
              serverPort: 8266
              inContainer: true
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
              limits:
                cpu: 2000m
    persistence:
      media:
        type: nfs
        server: voyager.internal
        path: /mnt/akademiya/data/metube
        globalMounts:
          - path: /mnt/media
    service:
      app:
        enabled: false
