# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr-node
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    controllers:
      tdarr-node:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node
              tag: 2.64.02@sha256:ac2486f5e3f6d2b0f6517e0c6b0a0cf6d2c75dc584d385d025a04613d4d34cae
            env:
              TZ: America/Edmonton
              serverIP: voyager.internal
              serverPort: 8266
              inContainer: true
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
              limits:
                cpu: 2000m
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: tdarr-node-gpu
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/gpus
                    operator: DoesNotExist
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        enabled: false
    persistence:
      media:
        type: nfs
        server: voyager.internal
        path: /mnt/akademiya/data/metube
        globalMounts:
          - path: /mnt/media
