---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-repository
spec:
  dependsOn:
    - name: kopiur
  healthCheckExprs:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      current: has(status.observedGeneration) && status.observedGeneration == metadata.generation && has(status.phase) && status.phase == 'Ready'
      failed: has(status.observedGeneration) && status.observedGeneration == metadata.generation && has(status.phase) && status.phase in ['Degraded', 'Failed']
      inProgress: '!has(status.observedGeneration) || status.observedGeneration != metadata.generation || !has(status.phase) || status.phase in [''Pending'', ''Initializing'']'
      kind: ClusterRepository
  interval: 1h
  path: ./kubernetes/apps/base/storage/kopiur-repository
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
