---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name miso-gallery
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        AUTH_TYPE: oidc
        OIDC_CALLBACK_URL: https://miso-gallery.jory.dev/auth/oidc/callback
        OIDC_CLIENT_ID: "{{ .MISO_GALLERY_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MISO_GALLERY_CLIENT_SECRET }}"
        OIDC_ENABLED: "true"
        OIDC_ISSUER: https://sso.jory.dev
        OIDC_PROVIDER_NAME: Authentik
  dataFrom:
    - extract:
        key: miso-gallery
