---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 15m
  dependsOn: []
  values:
    controllers:
      litellm:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/berriai/litellm
              tag: v1.83.10-stable@sha256:e47fce8933ed2534d5fe1e8d0cf3391b5f3baf11bebd4c21482ae11e0222e189
            args:
              - --config=/app/config.yaml
            env:
              LITELLM_LOG: INFO
              CHATGPT_TOKEN_DIR: /app/chatgpt_tokens
            envFrom:
              - secretRef:
                  name: litellm
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
    persistence:
      config:
        type: configMap
        name: litellm-configmap
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
      cache:
        type: emptyDir
        advancedMounts:
          litellm:
            app:
              - path: /app/cache
      ui:
        existingClaim: litellm
        globalMounts:
          - path: /app/chatgpt_tokens
    route:
      app:
        hostnames: ["litellm.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: 4000
