---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./litellmproxy.yaml
  - ./virtualkeys
  - ./llama-nvidia.yaml
  # - ./llama-nvidia-muse.yaml
  # - ./llama-flash-next.yaml
  - ./llama-strix.yaml
  # - ./llama-strix-dsv4f.yaml
  # - ./llama-strix-fp8.yaml
  - ./llama-reviewer.yaml
  - ./llama-vision.yaml
  - ./prometheusrule.yaml
  - ./llmkube-skirk-cache.yaml
  - ./servicemonitor.yaml
  - ./dashboard
  - ./models
