---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboard
  - ./models
  - ./virtualkeys
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./litellmproxy.yaml
  - ./llmkube-skirk-cache.yaml
  - ./muse-glimmer.yaml
  # - ./nemotron-3.5-lightning-30b-a3b.yaml
  - ./nvidia-pool.yaml
  # - ./qwen3.6-35b-a3b.yaml
  - ./qwen3.8-27b.yaml
  - ./qwen3.8-flash-next.yaml
  - ./prometheusrule.yaml
  - ./servicemonitor.yaml
