---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-strix-prompt-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 64Gi
