---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kapowarr
spec:
  chartRef:
    kind: OCIRepository
    name: kapowarr
  interval: 15m
  dependsOn: []
  values:
    controllers:
      kapowarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mrcas/kapowarr
              tag: v1.3.2@sha256:cd3f004caff59636dde73b06df5b2f8068b485b47ff5fe82f6129562c0f2ac3b
            env:
              TZ: America/Edmonton
            # securityContext:
            #   runAsUser: 1000
            #   runAsGroup: 100
            #   runAsNonRoot: true
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: false
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 15m
                memory: 100M
              limits:
                memory: 1G
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/db
      media:
        type: nfs
        server: voyager.internal
        path: /mnt/akademiya/data
        globalMounts:
          - path: /media
    route:
      app:
        hostnames: ["{{ .Release.Name }}.jory.dev"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 5656
