---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marketplace-browser-profile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 2Gi
