# yaml-language-server: $schema=https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#namespace-v1-core
apiVersion: v1
kind: Namespace
metadata:
  name: not-used
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    resource.kubernetes.io/admin-access: "true"
