# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        DISCORD_BOT_TOKEN: "{{ .MISO_BOT_TOKEN }}"
        SAFFRON_BOT_TOKEN: "{{ .SAFFRON_BOT_TOKEN }}"
        MATCHA_BOT_TOKEN: "{{ .MATCHA_BOT_TOKEN }}"
        GH_PAT: "{{ .ITS_MISO_PAT }}"
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        MOONSHOT_API_KEY: "{{ .MOONSHOT_API_KEY }}"
        DISCORD_ADMIN_USER_ID: "{{ .DISCORD_ADMIN_USER_ID }}"
        DISCORD_SERVER_ID: "{{ .DISCORD_SERVER_ID }}"
        MATCHA_CHANNEL_ID: "{{ .MATCHA_CHANNEL_ID }}"
        COMPOSIO_API_KEY: "{{ .COMPOSIO_API_KEY }}"
        LITELLM_API_KEY: "{{ .LITELLM_API_KEY }}"
        OPENAI_CODEX_USERNAME: "{{ .username }}"
  dataFrom:
    - extract:
        key: openclaw
    - extract:
        key: composio
    - extract:
        key: github-miso
    - extract:
        key: minimax
    - extract:
        key: moonshot
    - extract:
        key: litellm
      rewrite:
        - regexp:
            source: ^password$
            target: LITELLM_API_KEY
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name huggingface
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        HF_TOKEN: "{{ .HF_TOKEN }}"
  dataFrom:
  - extract:
      key: HuggingFace
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name openclaw-actual
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        ACTUAL_SYNC_ID: "{{ .ACTUAL_SYNC_ID }}"
        ACTUAL_PASSWORD: "{{ .password }}"
  dataFrom:
  - extract:
      key: actual
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name openclaw-miso-gallery
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        MISO_GALLERY_API_KEY: "{{ .LLM_API_KEYS }}"
  dataFrom:
    - extract:
        key: miso-gallery
