---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: openclaw-chart-renderer
    files:
      - chart-renderer/package.json
      - chart-renderer/package-lock.json
      - chart-renderer/openclaw.plugin.json
      - chart-renderer/tsconfig.json
      - chart-renderer/src/index.ts
generatorOptions:
  disableNameSuffixHash: true
#  openclaw models auth login --provider openai
