---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: grafana
spec:
  url: http://mcp-grafana.observability:8000/sse
  transport: sse
  groupRef: mcp-tools
