---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./memini-rerank.yaml
  - ./memini-rerank-1.yaml
  - ./memini-rerank-2.yaml
  - ./memini-rerank-3.yaml
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
