---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: ha-mcp
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:7.14.1
  transport: streamable-http
  groupRef:
    name: mcp-tools
  env:
    - name: HOMEASSISTANT_URL
      value: https://hass.jory.dev
  secrets:
    - name: toolhive-home-assistant
      key: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
