---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: repo-wiki-secret-key
spec:
  length: 48
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name repo-wiki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        OPENAI_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
        SECRET_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: litellm
    - extract:
        key: github-miso
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: repo-wiki-secret-key
