---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ${APP}-weekly
spec:
  schedule: "0 30 1 * * 0"
  backupOwnerReference: self
  cluster:
    name: ${APP}
