---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ${APP}-daily
spec:
  schedule: "40 4 * * *"
  backupOwnerReference: self
  cluster:
    name: ${APP}
