---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmkube-models
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 200Gi
