# MS-01 networking
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp2s0f0np0
rings:
  rx: 8160
  tx: 8160
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp2s0f1np1
rings:
  rx: 8160
  tx: 8160
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp87s0
up: true
addresses: []
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp90s0
up: true
addresses: []
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - enp2s0f0np0
bondMode: active-backup
miimon: 100
mtu: 9000
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.70
vlanID: 70
parent: bond0
mtu: 9000
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.90
vlanID: 90
parent: bond0
mtu: 9000
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: bond0
clientIdentifier: mac
---
# Shared across all MS-01s
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: disk.model == "WD_BLACK SN770 1TB" && !system_disk
  minSize: 1TB
---
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
timeout: 5m
---
apiVersion: v1alpha1
kind: OOMConfig
triggerExpression: "false"
