---
schedule: service
action: remove
remove_from_client: false
service:
  interval: 2m
radarr:
  - name: main
    url: http://radarr.downloads.svc.cluster.local
    enabled: true
sonarr:
  - name: main
    url: http://sonarr.downloads.svc.cluster.local
    enabled: true
