---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app comfyui
spec:
  components:
    - ../../../../../components/gpu
    - ../../../../../components/kopiur/backup
  interval: 1h
  path: ./kubernetes/apps/base/llm/comfyui/app
  postBuild:
    substitute:
      APP: *app
      KOPIUR_HOSTNAME: llm
      CLUSTER: ${CLUSTER}
      KOPIUR_CAPACITY: 200Gi
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app miso-gallery
spec:
  components:
    - ../../../../../components/zeroscaler
  interval: 1h
  path: ./kubernetes/apps/base/llm/comfyui/miso-gallery
  postBuild:
    substitute:
      APP: *app
      CLUSTER: ${CLUSTER}
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
