# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app embed
spec:
  dependsOn:
    - name: llmkube
  healthCheckExprs:
    - apiVersion: inference.llmkube.dev/v1alpha1
      kind: InferenceService
      failed: status.phase != 'Ready'
      current: status.phase == 'Ready'
  interval: 1h
  path: ./kubernetes/apps/base/llm/embed
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
