---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: litellm
spec:
  components:
    - ../../../../../components/dragonfly
    - ../../../../../components/postgres
    - ../../../../../components/kopiur/backup
  dependsOn:
    - name: llmkube
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/base/llm/litellm/app
  postBuild:
    substitute:
      APP: litellm
      KOPIUR_HOSTNAME: llm
      KOPIUR_CAPACITY: 1Gi
      KOPIUR_ACCESSMODES: ReadWriteMany
      KOPIUR_STORAGECLASS: ceph-filesystem
      KOPIUR_SNAPSHOTCLASS: csi-ceph-filesystem
  wait: false
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
