---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    helm.sh/resource-policy: keep
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Gi
  storageClassName: local-hostpath
