---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deepwiki-config
data:
  embedder.json: |
    {
      "embedder": {
        "client_class": "OpenAIClient",
        "initialize_kwargs": {
          "api_key": "$${OPENAI_API_KEY}",
          "base_url": "$${OPENAI_BASE_URL}"
        },
        "batch_size": 10,
        "model_kwargs": {
          "model": "qwen3-embedding-0-6b",
          "dimensions": 1024,
          "encoding_format": "float"
        }
      },
      "retriever": {
        "top_k": 20
      },
      "text_splitter": {
        "split_by": "word",
        "chunk_size": 350,
        "chunk_overlap": 100
      }
    }
  generator.json: |
    {
      "default_provider": "openai",
      "providers": {
        "openai": {
          "default_model": "self-hosted",
          "supportsCustomModel": true,
          "models": {
            "self-hosted": {
              "temperature": 0.7,
              "top_p": 0.8
            }
          }
        }
      }
    }
