---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: llama-memory
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: llama-memory
      app.kubernetes.io/instance: llama-memory
  podTargetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
  podMetricsEndpoints:
    - port: http
      path: /metrics
      honorLabels: true
  namespaceSelector:
    matchNames:
      - llm
