---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name towonel-operator
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: towonel-operator-secret
    creationPolicy: Owner
  data:
    - secretKey: TOWONEL_API_KEY
      remoteRef:
        key: towonel-tunnel
        property: api_key
