---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: llama-server
spec:
  schema:
    name: OpenAI
  backendRef:
    name: llama-server
    kind: Backend
    group: gateway.envoyproxy.io
