---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: workadventure
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.30.6
  url: oci://ghcr.io/workadventure/helm-charts/workadventure
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: workadventure
spec:
  chartRef:
    kind: OCIRepository
    name: workadventure
  interval: 15m
  dependsOn: []
  valuesFrom:
    - kind: Secret
      name: workadventure
      valuesKey: MAP_STORAGE_API_TOKEN
      targetPath: commonSecretEnv.MAP_STORAGE_API_TOKEN
    - kind: Secret
      name: workadventure
      valuesKey: AUTHENTICATION_PASSWORD
      targetPath: mapstorage.secretEnv.AUTHENTICATION_PASSWORD
  values:
    domainName: gather.jory.dev
    singleDomain: true
    ingress:
      enabled: false
    commonEnv:
      WA_PROTO: https
      WA_HOST: gather.jory.dev
    play:
      env:
        DISABLE_ANONYMOUS: "true"
        OPENID_CLIENT_REDIRECT_URL: https://gather.jory.dev/@/oidc/callback
        OPENID_CLIENT_REDIRECT_LOGOUT_URL: https://gather.jory.dev
      envFrom:
        - secretRef:
            name: workadventure
