---
apiVersion: towonel.io/v1alpha1
kind: TowonelTunnel
metadata:
  name: towonel-${CLUSTER}
spec:
  apiKeySecretRef:
    name: towonel-operator-secret
    key: TOWONEL_API_KEY
  deletionPolicy: Retain
  region: CA
