---
name: caddy-l4

services:
  caddy:
    container_name: caddy-l4
    image: ghcr.io/bjw-s-labs/caddy-l4:2.11.4
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - caddy-config:/config
      - caddy-data:/data
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile

volumes:
  caddy-config:
  caddy-data:

configs:
  caddyfile:
    file: ./config/Caddyfile

networks:
  default:
    name: edge
    external: true
