---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui-tool-servers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        config.json: |
          {
            "mcpServers": {
              "homeassistant": {
                "type": "streamable-http",
                "url": "https://hass.jory.dev/api/mcp",
                "headers": {
                  "Authorization": "Bearer {{ .HOME_ASSISTANT_TOKEN }}",
                  "Accept": "application/json"
                }
              },
              "grafana": {
                "type": "sse",
                "url": "http://mcp-grafana.observability:8000/sse"
              }
            }
          }
  dataFrom:
    - extract:
        key: openclaw
