---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: dsv4f-1
spec:
  modelName: dsv4f
  proxyRef: litellm
  params:
    model: openai/deepseek-v4-flash
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_API_KEY
    additional:
      order: 1
  info:
    mode: chat
    maxInputTokens: 1000000
    maxOutputTokens: 16384
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      input_cost_per_token: 4.4e-07
      cache_creation_input_token_cost: 4.4e-07
      cache_read_input_token_cost: 1.4e-08
      output_cost_per_token: 1.32e-06
