---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: dsv4f-local
spec:
  modelName: dsv4f-local
  proxyRef: litellm
  params:
    model: openai/dsv4f-local
    apiBase: http://dsv4f-local.llm:8080/v1
    apiKey: dsv4f-local
    additional:
      additional_drop_params:
      - reasoning_effort
      max_parallel_requests: 1
  info:
    mode: chat
    maxInputTokens: 150000
    maxOutputTokens: 20480
    supportsFunctionCalling: true
    supportsVision: false
    extra:
      input_cost_per_token: 1.25e-07
      cache_creation_input_token_cost: 1.25e-07
      cache_read_input_token_cost: 1.25e-08
      output_cost_per_token: 4.999e-07
