---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: embed-pool-2
spec:
  modelName: embed
  proxyRef: litellm
  params:
    model: openai/embed
    apiBase: http://embed-2.llm:8080/v1
    apiKey: sk-llmkube-noauth
  info:
    maxInputTokens: 32768
