---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: frontier-pool-5
spec:
  modelName: frontier-pool
  proxyRef: litellm
  params:
    model: openai/glm-5.2
    apiBase: https://api.neuralwatt.com/v1
    apiKey: os.environ/NEURALWATT_API_KEY
    additional:
      order: 5
  info:
    mode: chat
    maxInputTokens: 1048560
    maxOutputTokens: 16384
    supportsFunctionCalling: true
    extra:
      input_cost_per_token: 1.1688e-07
      output_cost_per_token: 1.1688e-07
