---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: frontier-pool-1
spec:
  modelName: frontier-pool
  proxyRef: litellm
  params:
    model: chatgpt/gpt-6-astra
    additional:
      additional_drop_params:
      - temperature
      order: 1
  info:
    mode: responses
    maxInputTokens: 272000
    maxOutputTokens: 128000
    supportsVision: true
    supportsPromptCaching: true
    extra:
      input_cost_per_token: 1.0e-05
      cache_creation_input_token_cost: 1.25e-05
      cache_read_input_token_cost: 1.0e-06
      output_cost_per_token: 5.0e-05
