---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: frontier-pool-4
spec:
  modelName: frontier-pool
  proxyRef: litellm
  params:
    model: openai/deepseek-v4-flash
    apiBase: https://api.neuralwatt.com/v1
    apiKey: os.environ/NEURALWATT_API_KEY
    additional:
      order: 4
  info:
    mode: chat
    maxInputTokens: 1000000
    maxOutputTokens: 16384
    supportsFunctionCalling: true
    extra:
      input_cost_per_token: 5.77e-08
      output_cost_per_token: 5.77e-08
