---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: glm-5.2
spec:
  modelName: glm-5.2
  proxyRef: litellm
  params:
    model: openai/glm-5.2
    apiBase: https://api.neuralwatt.com/v1
    apiKey: os.environ/NEURALWATT_API_KEY
    additional:
      order: 2
  info:
    mode: chat
    maxInputTokens: 1048560
    maxOutputTokens: 16384
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      input_cost_per_token: 1.45e-06
      cache_creation_input_token_cost: 1.45e-06
      cache_read_input_token_cost: 3.6e-07
      output_cost_per_token: 4.5e-06
