---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: implementation-pool-2
spec:
  modelName: implementation-pool
  proxyRef: litellm
  params:
    model: openai/MiniMax-M2.7
    apiBase: https://api.minimax.io/v1
    apiKey: os.environ/MINIMAX_API_KEY
    additional:
      order: 2
  info:
    mode: chat
    maxInputTokens: 204800
    maxOutputTokens: 32768
    supportsFunctionCalling: true
    extra:
      input_cost_per_token: 3.0e-07
      output_cost_per_token: 1.2e-06
