---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: kimi-k3-1
spec:
  modelName: kimi-k3
  proxyRef: litellm
  params:
    model: openai/k3
    apiBase: https://api.kimi.com/coding/v1
    apiKey: os.environ/KIMI_CODE_API_KEY
    additional:
      order: 1
      additional_drop_params:
      - frequency_penalty
      - n
      - presence_penalty
      - temperature
      - thinking
      - top_p
  info:
    mode: chat
    maxInputTokens: 1048576
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
    supportsVision: true
    extra:
      input_cost_per_token: 3.0e-06
      cache_creation_input_token_cost: 3.0e-06
      cache_read_input_token_cost: 3.0e-07
      output_cost_per_token: 1.5e-05
