---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: local-pool-1
spec:
  modelName: local-pool
  proxyRef: litellm
  params:
    model: openai/llama-nvidia
    apiBase: http://llama-nvidia.llm.svc.cluster.local:8080/v1
    apiKey: sk-llmkube-noauth
    additional:
      temperature: 1.0
      top_p: 0.95
      top_k: 20
      min_p: 0
      order: 1
      max_parallel_requests: 1
  info:
    mode: chat
    maxInputTokens: 131072
    maxOutputTokens: 40960
    supportsFunctionCalling: true
    supportsVision: true
