---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: local-pool-chat-2
spec:
  modelName: local-pool-chat
  proxyRef: litellm
  params:
    model: openai/gemma-4-12b-it-qat
    apiBase: http://smurf-pc.internal:1234/v1
    apiKey: sk-noauth
    additional:
      temperature: 1.0
      top_p: 0.95
      top_k: 64
      reasoning_effort: none
      order: 2
      max_parallel_requests: 4
      allowed_openai_params:
        - reasoning_effort
  info:
    mode: chat
    maxInputTokens: 262144
    maxOutputTokens: 16384
    supportsFunctionCalling: true
    supportsVision: true
