---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: local-pool-3
spec:
  modelName: local-pool
  proxyRef: litellm
  params:
    model: openai/llama-strix
    apiBase: http://llama-strix.llm.svc.cluster.local:8080/v1
    apiKey: sk-llmkube-noauth
    additional:
      temperature: 1.0
      top_p: 0.95
      top_k: 20
      min_p: 0
      order: 3
  info:
    mode: chat
    maxInputTokens: 262144
    maxOutputTokens: 20480
    supportsFunctionCalling: true
    supportsVision: true
