---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: memini-embed
spec:
  modelName: memini-embed
  proxyRef: litellm
  params:
    model: openai/memini-embed
    apiBase: http://memini-embed.llm:8080/v1
    apiKey: memini-embed
  info:
    mode: embedding
    extra:
      input_cost_per_token: 1.0e-08
      output_cost_per_token: 0.0
