---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: mimo-v2.5
spec:
  modelName: mimo-v2.5
  proxyRef: litellm
  params:
    model: openai/mimo-v2.5
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_API_KEY
  info:
    mode: chat
    maxInputTokens: 262144
    maxOutputTokens: 16384
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      input_cost_per_token: 1.4e-07
      cache_creation_input_token_cost: 1.4e-07
      cache_read_input_token_cost: 2.8e-09
      output_cost_per_token: 2.8e-07
