---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: nvidia
spec:
  modelName: nvidia
  proxyRef: litellm
  params:
    model: openai/llama-nvidia
    apiBase: http://llama-nvidia.llm:8080/v1
    apiKey: llama-nvidia
    additional:
      additional_drop_params:
      - reasoning_effort
      max_parallel_requests: 1
  info:
    mode: chat
    maxInputTokens: 140000
    maxOutputTokens: 40960
    supportsFunctionCalling: true
    supportsVision: true
    extra:
      input_cost_per_token: 2.162e-07
      cache_creation_input_token_cost: 2.162e-07
      cache_read_input_token_cost: 2.16e-08
      output_cost_per_token: 8.649e-07
