---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: qwen3.8-max
spec:
  modelName: qwen3.8-max
  proxyRef: litellm
  params:
    model: openai/qwen3.8-max
    apiBase: https://opencode.ai/zen/go/v1
    apiKey: os.environ/OPENCODE_API_KEY
  info:
    mode: chat
    maxInputTokens: 1000000
    maxOutputTokens: 32768
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      input_cost_per_token: 2.0e-06
      cache_creation_input_token_cost: 2.5e-06
      cache_read_input_token_cost: 2.5e-07
      output_cost_per_token: 6.0e-06
