---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: reasoning-pool-1
spec:
  modelName: reasoning-pool
  proxyRef: litellm
  params:
    model: chatgpt/gpt-5.6-terra
    additional:
      additional_drop_params:
      - temperature
      order: 1
  info:
    mode: responses
    maxInputTokens: 1050000
    extra:
      input_cost_per_token: 2.0e-06
      cache_creation_input_token_cost: 2.5e-06
      cache_read_input_token_cost: 2.0e-07
      output_cost_per_token: 1.2e-05
