---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: rerank
spec:
  modelName: rerank
  proxyRef: litellm
  params:
    model: infinity/memini-rerank
    apiBase: http://memini-rerank.llm:8080
    apiKey: memini-rerank
  info:
    mode: rerank
    extra:
      input_cost_per_token: 1.0e-08
      output_cost_per_token: 0.0
