---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: strix-fp8
spec:
  modelName: strix-fp8
  proxyRef: litellm
  params:
    model: openai/llama-strix-fp8
    apiBase: http://llama-strix-fp8.llm:8080/v1
    apiKey: llama-strix-fp8
    additional:
      additional_drop_params:
      - reasoning_effort
      max_parallel_requests: 2
      timeout: 3600
