---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: toolhive-embed
spec:
  modelName: toolhive-embed
  proxyRef: litellm
  params:
    model: openai/toolhive-embed
    apiBase: http://toolhive-embed.llm:8080/v1
    apiKey: toolhive-embed
  info:
    mode: embedding
    extra:
      input_cost_per_token: 1.0e-08
      output_cost_per_token: 0.0
