---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoymiles-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: hoymiles-exporter
  interval: 15m
  dependsOn: []
  values:
    controllers:
      hoymiles-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/hoymiles-exporter
              tag: 0.1.1@sha256:57422625f61d3c413827213ec7e06d1f3098fe78f28bb8a1e3e206aaef2c2e04
            env:
              DTU_HOST: solar.internal
              TZ: America/Edmonton
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
    service:
      app:
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9099
        annotations:
          external-dns.alpha.kubernetes.io/hostname: exporters.jory.dev
