---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
spec:
  chartRef:
    kind: OCIRepository
    name: it-tools
  interval: 15m
  dependsOn: []
  values:
    controllers:
      it-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/joryirving/it-tools
              tag: 2026.9.27@sha256:b970b44ed9b1d3f74eee603560e62307f70f3744f88c2937c292207a63ad9ce4
            env:
              TZ: America/Edmonton
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
            fsGroup: 100
            fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      tmpfs:
        type: emptyDir
        advancedMounts:
          it-tools:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames: ["tools.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
