---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name workadventure
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        OPENID_CLIENT_ID: "{{ .WORKADVENTURE_OIDC_CLIENT_ID }}"
        OPENID_CLIENT_SECRET: "{{ .WORKADVENTURE_OIDC_CLIENT_SECRET }}"
        OPENID_CLIENT_ISSUER: "https://sso.jory.dev/application/o/workadventure/"
        SECRET_KEY: "{{ .WORKADVENTURE_SECRET_KEY }}"
        MAP_STORAGE_API_TOKEN: "{{ .WORKADVENTURE_MAP_STORAGE_TOKEN }}"
        AUTHENTICATION_PASSWORD: "{{ .WORKADVENTURE_MAPSTORAGE_AUTH_PASSWORD }}"
        MATRIX_ADMIN_PASSWORD: "{{ .MATRIX_ADMIN_PASSWORD }}"
        TURN_STATIC_AUTH_SECRET: "{{ .WORKADVENTURE_TURN_AUTH_SECRET }}"
        LIVEKIT_API_KEY: "{{ .LIVEKIT_API_KEY }}"
        LIVEKIT_API_SECRET: "{{ .LIVEKIT_API_SECRET }}"
  dataFrom:
    - extract:
        key: workadventure
    - extract:
        key: matrix
