---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: free-game-notifier
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 15m
  dependsOn: []
  values:
    controllers:
      free-game-notifier:
        containers:
          app:
            image:
              repository: ghcr.io/ctrl-research/free-games
              tag: v0.0.4@sha256:691dd09722c6015af0dadaa7900b09fd5f4c1376cd8804bb998dca3e2efa550b
            env:
              TZ: America/Edmonton
              EPIC_INCLUDE_UPCOMING: "false"
              ENABLE_STEAM: "true"
              ENABLE_TWITCH_DROPS: "true"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}"
