---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fenrir
spec:
  interval: 1h
  ref:
    commit: fd91750567dc038b0f608bd86be7bb335601aab0
  url: https://github.com/shrinedogg/fenrir
