---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minecraft
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.3
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-vibecraft
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft
  interval: 15m
  dependsOn: []
  values:
    extraEnv:
      TZ: America/Edmonton
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.5.4@sha256:f364bae78a0027aee72b01b9b532b1ae0990b3ee8cadbb6a3bc25db77418a25f
    livenessProbe:
      initialDelaySeconds: 30
    minecraftServer:
      eula: true
      # renovate: datasource=custom.minecraft-release
      version: 26.1.2
      type: PAPER
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      #whitelist: "LilDrunkenSmurf"
      ops: "LilDrunkenSmurf"
      motd: "Vibecraft. Come hang out and Vibe"
      worldSaveName: Vibecraft
      viewDistance: 12
      spigetResources:
        - 36618 #Prom Exporter
      rcon:
        enabled: true
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    readinessProbe:
      initialDelaySeconds: 30
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 2000m
        memory: 4Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 100
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: vibecraft.jory.dev
    startupProbe:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: RCON_PASSWORD
      targetPath: minecraftServer.rcon.password
