---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  chartRef:
    kind: OCIRepository
    name: headlamp
  interval: 15m
  dependsOn: []
  values:
    clusterRoleBinding:
      create: false
    config:
      pluginsDir: /build/plugins
    fullnameOverride: headlamp
    initContainers:
      - image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.7.0@sha256:636c7a5ae0d4eb196c192f8f1cde06f20f1f5ebdf1863f6e57d22444d8b8360c
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    podAnnotations:
      reloader.stakater.com/auto: "true"
    serviceAccount:
      create: false
      name: headlamp-admin
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
