---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name coturn
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        TOWONEL_VPS_IP: "{{ .TOWONEL_VPS_IP }}"
        TURN_STATIC_AUTH_SECRET: "{{ .WORKADVENTURE_TURN_AUTH_SECRET }}"
  data:
    - secretKey: TOWONEL_VPS_IP
      remoteRef:
        key: towonel-tunnel
        property: TOWONEL_VPS_IP
  dataFrom:
    - extract:
        key: workadventure
