---
apiVersion: grafana.integreatly.org/v1alpha1
kind: GrafanaPlugin
metadata:
  name: victoriametrics-logs
spec:
  plugin:
    name: victoriametrics-logs-datasource
    version: "0.26.2"
    source:
      registry: "grafana"
