---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name towonel-agent-config
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: TOWONEL_VPS_IP
      remoteRef:
        key: towonel-tunnel
        property: TOWONEL_VPS_IP
    - secretKey: TOWONEL_VPS_IPV6
      remoteRef:
        key: towonel-tunnel
        property: TOWONEL_VPS_IPV6
