---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
machine:
  install:
    diskSelector:
      serial: "YMA62T0KA24174069L"
  nodeLabels:
    topology.kubernetes.io/gpus: amd
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: skirk

