---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  name: pr-review
spec:
  proxyRef: litellm
  keyAlias: Github Actions PR Reviewer
  secretName: litellm-key-pr-review
  secretKey: api-key
  models:
  - local-pool
  - local-pool-chat
  - llama-nvidia
  - llama-nvidia-chat
  - llama-reviewer
  - llama-reviewer-chat
  - llama-strix
  - llama-strix-chat
  - MiniMax-M2.7
  - MiniMax-M3
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pr-review
spec:
  secretStoreRefs:
  - name: onepassword
    kind: ClusterSecretStore
  selector:
    secret:
      name: litellm-key-pr-review
  data:
  - match:
      secretKey: api-key
      remoteRef:
        remoteKey: litellm
        property: LITELLM_PR_REVIEW_API_KEY
