---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  name: repo-wiki
spec:
  proxyRef: litellm
  keyAlias: Repo-Wiki
  secretName: litellm-key-repo-wiki
  secretKey: api-key
  models:
  - local-pool-chat
  - llama-strix-chat
  - llama-nvidia-chat
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: repo-wiki
spec:
  secretStoreRefs:
  - name: onepassword
    kind: ClusterSecretStore
  selector:
    secret:
      name: litellm-key-repo-wiki
  data:
  - match:
      secretKey: api-key
      remoteRef:
        remoteKey: litellm
        property: LITELLM_REPO_WIKI_API_KEY
