---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  name: zed
spec:
  proxyRef: litellm
  keyAlias: Zed
  secretName: litellm-key-zed
  secretKey: api-key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: zed
spec:
  secretStoreRefs:
  - name: onepassword
    kind: ClusterSecretStore
  selector:
    secret:
      name: litellm-key-zed
  data:
  - match:
      secretKey: api-key
      remoteRef:
        remoteKey: litellm
        property: LITELLM_ZED_API_KEY
