{
 "title": "Wunderground PWS Weather",
 "description": "Access current weather data for your PWS, exported from Wunderground!",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wunderground_metric_temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wunderground_metric_windSpeed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wunderground_observations_winddir",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "wind_deg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wunderground_observations_humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wunderground_metric_pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_name, $tag_sys_country",
     "expr": "wunderground_metric_temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_country" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Temperature",
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "alias": "$tag_name, $tag_sys_country",
     "expr": "wunderground_metric_windSpeed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_country" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Wind Speed",
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "$tag_name, $tag_sys_country",
     "expr": "wunderground_metric_pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_country" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Atmospheric Pressure",
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name, $tag_sys_country",
     "expr": "wunderground_observations_humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_country" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Humidity",
     "measurement": "openweathermap",
     "select": [
      [
       { "params": [ "main_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  }
 ]
}