---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/embeddingserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: mcp-tools-embedding
spec:
  model: BAAI/bge-base-en-v1.
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-ipex-latest@sha256:0385886868dfb12ecebfe6975173aeb2b5c24a068ff2da35937451bfad8ec5ea
  env:
    - name: HOSTNAME
      value: "::"
