---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/embeddingserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: EmbeddingServer
metadata:
  name: mcp-tools-embedding
spec:
  model: Qwen/Qwen3-Embedding-0.6B
  image: ghcr.io/huggingface/text-embeddings-inference:xpu-ipex-latest@sha256:83f55427dd1b6379816fca6c6616f1a46afc7ad95139f3f0792af332ade0e90a
  env:
    - name: HOSTNAME
      value: "::"
    - name: ONEAPI_DEVICE_SELECTOR
      value: level_zero:gpu
    - name: UR_L0_ENABLE_RELAXED_ALLOCATION_LIMITS
      value: "1"
    - name: ZES_ENABLE_SYSMAN
      value: "1"
  podTemplateSpec:
    spec:
      containers:
        - name: embedding
          resources:
            claims:
              - name: gpu
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: toolhive-config-gpu
