---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcptelemetryconfig_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPTelemetryConfig
metadata:
  name: prometheus
  namespace: llm
spec:
  prometheus:
    enabled: true
