---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpexternalauthconfig_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPExternalAuthConfig
metadata:
  name: home-assistant-auth
spec:
  type: bearerToken
  bearerToken:
    tokenSecretRef:
      name: toolhive-home-assistant
      key: token
