---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpoidcconfig_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPOIDCConfig
metadata:
  name: mcp-gateway
spec:
  inline:
    issuer: https://mcp.jory.dev
  type: inline
