---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: home-assistant
spec:
  remoteURL: https://hass.jory.dev/api/mcp
  transport: streamable-http
  groupRef: mcp-tools
  externalAuthConfigRef:
    name: home-assistant-auth
  headerForward:
    addPlaintextHeaders:
      Accept: application/json
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: grafana
spec:
  remoteURL: http://mcp-grafana.observability:8000/sse
  transport: sse
  groupRef: mcp-tools
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: searxng
spec:
  remoteURL: http://mcp-searxng.llm:3000/mcp
  transport: streamable-http
  groupRef: mcp-tools
