---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: home-assistant
spec:
  remoteURL: https://hass.jory.dev/api/mcp
  transport: streamable-http
  groupRef: mcp-tools
  headerForward:
    addPlaintextHeaders:
      Accept: application/json
    addHeadersFromSecret:
      - headerName: Authorization
        valueSecretRef:
          name: toolhive-home-assistant
          key: bearer-token
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: grafana
spec:
  remoteURL: http://mcp-grafana.observability.svc.cluster.local:8000/sse
  transport: sse
  groupRef: mcp-tools
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/toolhive.stacklok.dev/mcpserverentry_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServerEntry
metadata:
  name: searxng
spec:
  remoteURL: http://mcp-searxng.llm.svc.cluster.local:3000
  transport: streamable-http
  groupRef: mcp-tools
