---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-direct
spec:
  groupRef:
    name: mcp-direct
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
