apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-internal
spec:
<<<<<<< HEAD
<<<<<<< HEAD
  groupRef:
    name: mcp-tools
=======
>>>>>>> parent of 1d36c3d8d (update toolhive CRDs)
=======
  groupRef: mcp-tools
>>>>>>> parent of 9a2df31fe (fix vmcp)
  config:
    groupRef: mcp-tools
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  embeddingServerRef:
    name: mcp-tools-embedding
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
