---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: komga
spec:
  chartRef:
    kind: OCIRepository
    name: komga
  interval: 15m
  dependsOn: []
  values:
    controllers:
      komga:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gotson/komga
              tag: 1.25.0@sha256:c4f9885fc077e2e9cd684dc95e8f6cfa5e33b100b46712b2de7f5cc2ff59e6fb
            env:
              TZ: America/Edmonton
              SERVER_PORT: &port 80
            resources:
              requests:
                cpu: 15m
                memory: 1Gi
              limits:
                memory: 4Gi
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: voyager.internal
        path: /mnt/akademiya/data
        globalMounts:
          - path: /data
            subPath: media
    route:
      app:
        hostnames: ["{{ .Release.Name }}.jory.dev"]
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
