# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name acarsdrama
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        ACARSDRAMA_ACARS: "{{ .ACARSDRAMA_ACARS }}"
        ACARSDRAMA_VDLM2: "{{ .ACARSDRAMA_VDLM2 }}"
  dataFrom:
    - extract:
        key: acars
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name acars-processor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK }}"
        LATITUDE: "{{ .LATITUDE }}"
        LONGITUDE: "{{ .LONGITUDE }}"
  dataFrom:
    - extract:
        key: acars
