---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name livekit
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        LIVEKIT_CONFIG: |
          port: 7880
          rtc:
            tcp_port: 7881
            udp_port: 7882
            use_external_ip: false
            node_ip: {{ .TOWONEL_VPS_IP }}
          keys:
            {{ .LIVEKIT_API_KEY }}: {{ .LIVEKIT_API_SECRET }}
          logging:
            json: true
            level: info
  data:
    - secretKey: TOWONEL_VPS_IP
      remoteRef:
        key: towonel-tunnel
        property: TOWONEL_VPS_IP
  dataFrom:
    - extract:
        key: workadventure
