---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workadventure
components:
  - ../../../components/namespace
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - ./livekit.yaml
  - ./synapse.yaml
  - ./workadventure.yaml
