---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com_litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: grafana
spec:
  alias: grafana
  params:
    allow_all_keys: false
    server_id: grafana
  proxyNamespace: llm
  proxyRef: litellm
  transport: sse
  url: http://mcp-grafana.observability:8000/sse
