---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./arr.yaml
  - ./dispatch.yaml
  - ./externalsecrets.yaml
  - ./flux-rbac.yaml
  - ./flux.yaml
  - ./grafana.yaml
  - ./github.yaml
  - ./ha.yaml
  - ./kubectl.yaml
  - ./marketplace-configmap.yaml
  - ./marketplace-pvc.yaml
  - ./marketplace.yaml
  - ./plan-shop-eat.yaml
  - ./rbac.yaml
  - ./seerr.yaml
  - ./talos.yaml
  - ./talosserviceaccount.yaml
  - ./unifi-network.yaml
