---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com_litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: plan-shop-eat
spec:
  alias: plan_shop_eat
  authType: bearer_token
  authTokenRef:
    key: Authorization
    name: plan-shop-eat
  params:
    allow_all_keys: false
    server_id: plan_shop_eat
  proxyNamespace: llm
  proxyRef: litellm
  transport: http
  url: https://planshopeat.netlify.app/mcp
