---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name home-ops-runner-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        github_app_id: '{{ .BOT_APP_ID }}'
        github_app_installation_id: '{{ .BOT_APP_INSTALLATION_ID }}'
        github_app_private_key: '{{ .BOT_APP_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: github-bot
